#!/bin/sh
### BEGIN INIT INFO
# Provides:          adc_data_mediator_c_service
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ADC Data Mediator Service (C Version)
# Description:       Reads ADC frames from iic-3 and transmits them to TCP clients.
### END INIT INFO

# Path to your compiled C daemon executable
DAEMON_EXEC="/usr/bin/adc_data_mediator" # 

NAME="adc_data_mediator_c_service" # Name of this init script
DESC="ADC Data Mediator Service (C Version)"

case "$1" in
  start)
    echo "Starting $DESC..."
    nohup "$DAEMON_EXEC" start > /dev/null 2>&1 &
    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
        echo "$DESC started successfully."
    else
        echo "$DESC failed to start."
    fi
    ;;

  stop)
    echo "Stopping $DESC..."
    "$DAEMON_EXEC" stop
    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
        echo "$DESC stopped successfully."
    else
        echo "$DESC failed to stop."
    fi
    ;;

  status)
    "$DAEMON_EXEC" status
    RETVAL=$?
    ;;

  restart|force-reload)
    echo "Restarting $DESC..."
    "$DAEMON_EXEC" stop
    sleep 2
    "$DAEMON_EXEC" start
    RETVAL=$?
    ;;

  *)
    echo "Usage: $0 {start|stop|restart|force-reload|status}" >&2
    exit 3
    ;;
esac

exit $RETVAL
